export const calculatorProps = [
    {value: "C", isLargeButton: true, fontWeigth:"fw-bold"},
    {value: "/", isLargeButton: false, fontWeigth:"fw-bolder"},
    {value: "*", isLargeButton: false, fontWeigth:"fw-bolder"},
    {value: 7, isLargeButton: false, fontWeigth:"fw-regular"},
    {value: 8, isLargeButton: false, fontWeigth:"fw-regular"},
    {value: 9, isLargeButton: false, fontWeigth:"fw-regular"},
    {value: "-", isLargeButton: false, fontWeigth:"fw-bolder"},
    {value: 4, isLargeButton: false, fontWeigth:"fw-regular"},
    {value: 5, isLargeButton: false, fontWeigth:"fw-regular"},
    {value: 6, isLargeButton: false, fontWeigth:"fw-regular"},
    {value: "+", isLargeButton: false, fontWeigth:"fw-bold"},
    {value: 1, isLargeButton: false, fontWeigth:"fw-regular"},
    {value: 2, isLargeButton: false, fontWeigth:"fw-regular"},
    {value: 3, isLargeButton: false, fontWeigth:"fw-regular"},
    {value: "=", isLargeButton: false, fontWeigth:"fw-regular", doubleHeight:true},
    {value: 0, isLargeButton: true, fontWeigth:"fw-regular"},
    {value: ".", isLargeButton: false, fontWeigth:"fw-regular"},
]